name: 🚀 Normalize and Patch Data

on:
  workflow_dispatch:

jobs:
  normalize_and_patch:
    runs-on: ubuntu-latest
    # ENSURE there is NO 'defaults:' section or 'working-directory:' line here.
    # This remains critical.

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # Use a stable version, v3 or v4 are common

      - name: Setup Python
        uses: actions/setup-python@v5 # Use a stable version, v4 or v5 are common
        with:
          python-version: '3.10' # Confirmed and fixed Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming 'requirements.txt' is in the root of your 'doorloop_sync_backend' repo.
          pip install -r requirements.txt

      - name: 🐍 Print Python Version (Sanity Check)
        run: python --version

      # NEW DIAGNOSTIC STEP: Check Working Directory and File Contents
      - name: 🔍 Debug Working Directory and File Contents
        run: |
          echo "--- Current Working Directory (pwd) ---"
          pwd
          echo "--- Contents of Current Directory (ls -F) ---"
          ls -F
          echo "--- Contents of 'scripts/' (ls -F scripts/) ---"
          ls -F scripts/
          echo "--- Value of GITHUB_WORKSPACE ---"
          echo "${{ github.workspace }}"
          echo "---------------------------------"
          # IMPORTANT: Check if the full expected path exists using 'stat'
          echo "--- Stat of the expected script path ---"
          stat "${{ github.workspace }}/scripts/normalize_and_patch_all.py" || echo "ERROR: Stat failed for script path. File likely not found."
          echo "----------------------------------------"


      - name: 🧠 Run Normalization Pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PYTHONPATH: .:${PYTHONPATH}
        run: |
          # ULTIMATE FIX ATTEMPT: Use GITHUB_WORKSPACE for an absolute path.
          # This should provide the correct, non-duplicated path.
          echo "Attempting to run script from: ${{ github.workspace }}/scripts/normalize_and_patch_all.py"
          # Using bash -c to ensure no shell interpretation issues with the path string
          # And adding 'set -x' for extreme verbosity on this command.
          /usr/bin/bash -c "set -x; python \"${{ github.workspace }}/scripts/normalize_and_patch_all.py\""