name: 🔄 DoorLoop → Supabase Sync
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks-out your repository so the job can access your scripts
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3 (Crucial): Installs the python libraries from your requirements.txt file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Runs your script with the secrets mapped as environment variables
      - name: Sync DoorLoop data
        run: python sync_all_doorloop_to_supabase.py
        env:
          DOORLOOP_API_KEY: ${{ secrets.DOORLOOP_API_KEY }}
          DOORLOOP_API_BASE_URL: ${{ secrets.DOORLOOP_API_BASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}