CREATE OR REPLACE VIEW doorloop_normalized_properties AS
SELECT
  r.id AS raw_id,
  r.doorloop_id,
  (r.payload_json->>'name')::TEXT AS name,
  (r.payload_json->>'type')::TEXT AS type,
  (r.payload_json->>'class')::TEXT AS class,
  (r.payload_json->>'active')::BOOLEAN AS active,
  (r.payload_json->>'description')::TEXT AS description,
  (r.payload_json->>'externalId')::TEXT AS external_id,
  (r.payload_json->>'managerId')::TEXT AS manager_id,
  (r.payload_json->>'purchaseDate')::DATE AS purchase_date,
  (r.payload_json->>'purchasePrice')::NUMERIC AS purchase_price,
  (r.payload_json->>'currentValue')::NUMERIC AS current_value,
  (r.payload_json->>'bedroomCount')::INTEGER AS bedroom_count,
  (r.payload_json->'address'->>'street1')::TEXT AS address_street1,
  (r.payload_json->'address'->>'street2')::TEXT AS address_street2,
  (r.payload_json->'address'->>'city')::TEXT AS address_city,
  (r.payload_json->'address'->>'state')::TEXT AS address_state,
  (r.payload_json->'address'->>'zip')::TEXT AS address_zip,
  (r.payload_json->'address'->>'country')::TEXT AS address_country,
  (r.payload_json->'address'->>'lat')::TEXT AS address_lat,
  (r.payload_json->'address'->>'lng')::TEXT AS address_lng,
  (r.payload_json->'address'->>'isValidAddress')::BOOLEAN AS address_is_valid,
  (r.payload_json->'owners')::JSONB AS owners_json,
  (r.payload_json->'pictures')::JSONB AS pictures_json,
  (r.payload_json->'amenities')::JSONB AS amenities_json,
  (r.payload_json->'settings'->'customFields')::JSONB AS custom_fields_json,
  (r.payload_json->'boardMembers')::JSONB AS board_members_json,
  (r.payload_json->'insurance')::JSONB AS insurance_json,
  (r.payload_json->'taxInfo')::JSONB AS tax_info_json,
  (r.payload_json->'financials')::JSONB AS financials_json,
  (r.payload_json->'compliance')::JSONB AS compliance_json,
  (r.payload_json->>'createdAt')::TIMESTAMP WITH TIME ZONE AS created_at,
  (r.payload_json->>'updatedAt')::TIMESTAMP WITH TIME ZONE AS updated_at
FROM doorloop_raw_properties r
WHERE r.doorloop_id IS NOT NULL;
