CREATE OR REPLACE VIEW doorloop_normalized_leases AS
SELECT
  r.id AS raw_id,
  r.doorloop_id,
  (r.payload_json->>'name')::TEXT AS name,
  (r.payload_json->>'start')::DATE AS start_date,
  (r.payload_json->>'end')::DATE AS end_date,
  (r.payload_json->>'term')::TEXT AS term,
  (r.payload_json->>'status')::TEXT AS status,
  (r.payload_json->>'evictionPending')::BOOLEAN AS eviction_pending,
  (r.payload_json->>'rolloverToAtWill')::BOOLEAN AS rollover_to_at_will,
  (r.payload_json->>'proofOfInsuranceRequired')::BOOLEAN AS proof_of_insurance_required,
  (r.payload_json->>'totalBalanceDue')::NUMERIC AS total_balance_due,
  (r.payload_json->>'totalDepositsHeld')::NUMERIC AS total_deposits_held,
  (r.payload_json->>'totalRecurringRent')::NUMERIC AS total_recurring_rent,
  (r.payload_json->>'totalRecurringPayments')::NUMERIC AS total_recurring_payments,
  (r.payload_json->>'totalRecurringCredits')::NUMERIC AS total_recurring_credits,
  (r.payload_json->>'totalRecurringCharges')::NUMERIC AS total_recurring_charges,
  (r.payload_json->>'createdAt')::TIMESTAMP WITH TIME ZONE AS created_at,
  (r.payload_json->>'updatedAt')::TIMESTAMP WITH TIME ZONE AS updated_at,
  (SELECT id FROM properties p WHERE p.doorloop_id = (r.payload_json->>'property')) AS property_id,
  (SELECT id FROM units u WHERE u.doorloop_id = ((r.payload_json->'units'->>0))) AS unit_id,
  (SELECT id FROM tenants t WHERE t.doorloop_id = ((r.payload_json->'tenants'->>0))) AS tenant_id,
  (r.payload_json->'reference')::JSONB AS reference_json,
  (r.payload_json->'notes')::JSONB AS notes_json,
  (r.payload_json->'settings')::JSONB AS settings_json,
  (r.payload_json->'renewalInfo')::JSONB AS renewal_info_json,
  (r.payload_json->'customFields')::JSONB AS custom_fields_json,
  (r.payload_json->'petPolicy')::JSONB AS pet_policy_json,
  (r.payload_json->'addendums')::JSONB AS addendums_json,
  (r.payload_json->'cosigners')::JSONB AS cosigners_json,
  (r.payload_json->'utilities')::JSONB AS utilities_json,
  (r.payload_json->'proofOfInsuranceStatus')::JSONB AS insurance_status_json
FROM doorloop_raw_leases r
WHERE r.doorloop_id IS NOT NULL;
