name: Deploy sql-proxy Edge Function

on:
  workflow_dispatch:

jobs:
  deploy-sql-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase Project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy sql-proxy Function
        run: |
          echo "${{ secrets.DOTENV_BUILD }}" > .env.build
          supabase functions deploy sql-proxy --no-verify-jwt --env-file .env.build --force
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
