name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: empirecommandcenter-altus
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.'
