name: DealRoom — Deploy (OIDC)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "functions/**"
      - "host.json"
      - "requirements.txt"
      - ".github/workflows/dealroom_deploy.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: dealroom-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: altus-dealroom-api-func
    steps:
      - uses: actions/checkout@v4

      - name: Package app (zip)
        run: |
          zip -r functionapp.zip . \
            -x ".git/*" ".github/*" "*.pyc" "__pycache__/*" ".venv/*" "venv/*"

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Resolve resource group
        id: rg
        run: echo "val=$(az functionapp show -n $APP_NAME --query resourceGroup -o tsv)" >> $GITHUB_OUTPUT

      - name: Enable remote build flags
        run: |
          az functionapp config appsettings set \
            -g "${{ steps.rg.outputs.val }}" -n "$APP_NAME" \
            --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true ENABLE_ORYX_BUILD=true

      - name: Deploy Function App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: functionapp.zip
          slot-name: production
