
name: Deploy Functions (Raw File Mode)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload to Azure using FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: waws-prod-dm1-081.ftp.azurewebsites.windows.net
          username: ${{ secrets.AZURE_FTP_USERNAME }}
          password: ${{ secrets.AZURE_FTP_PASSWORD }}
          server-dir: /site/wwwroot/
