name: 🔧 Create install_dependencies_hardened.yml

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 🔧 Install Dependencies (Hardened)
        run: |
          echo "--- Python and Pip Paths ---"
          which python
          python --version
          which pip
          pip --version
          echo "--------------------------"

          python -m pip install --upgrade pip

          echo "--- Purging Pip Cache ---"
          pip cache purge || true
          echo "-------------------------"

          echo "--- Installing psycopg2-binary explicitly (forced, no cache) ---"
          pip install --no-cache-dir --force-reinstall psycopg2-binary==2.9.9 -v || exit 1
          echo "---------------------------------------------------------------"

          echo "--- Installing other dependencies from requirements.txt (no cache) ---"
          pip install --no-cache-dir -r requirements.txt -v || exit 1
          echo "--------------------------------------------------------------------"

          echo "--- Installed Packages (pip freeze) ---"
          pip freeze
          echo "---------------------------------------"

          echo "--- Psycopg2 Import Check ---"
          python -c "import psycopg2; print('✅ psycopg2 available')" || (echo "❌ psycopg2 import failed!" && exit 1)
          echo "-----------------------------"
