name: Lockdown Phase 4

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete deprecated Edge Function: sql-proxy
        run: |
          supabase functions delete sql-proxy || echo "Function may already be deleted"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Confirm Deployment Lockdown
        run: echo "✅ Phase 4 cleanup completed. Project locked and stabilized."
