name: Refresh Materialized Views

on:
  schedule:
    - cron: '0 7 * * *'  # 2am Central Time
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run refresher
        run: python cron/fix_materialized_views.py
        env:
          SQL_PROXY_SECRET: ${{ secrets.SQL_PROXY_SECRET }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
