name: Normalize and Patch All (Daily)
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  normalize_and_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run normalization
        run: python normalize_and_patch_all.py