name: Retry DLQ Records Nightly

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  retry-dlq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install psycopg2
        run: pip install psycopg2-binary

      - name: Run DLQ retry script
        env:
          SUPABASE_DIRECT_DB_URL: ${{ secrets.SUPABASE_DIRECT_DB_URL }}
        run: python cli/retry_dlq_records.py
