name: smoke
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke
        run: echo "ok"
