name: "🔐 Lockdown Phase 4"

on:
  workflow_dispatch:

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run lockdown script
        run: |
          chmod +x ./lockdown_phase4.sh
          ./lockdown_phase4.sh
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
