name: 🔐 Lockdown Phase 4
on:
  workflow_dispatch:
jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Clean SQL functions and remove proxy
        run: |
          supabase functions delete sql-proxy || echo "Already deleted"
          echo "✅ Lockdown complete."
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
