name: 🚀 Deploy Excel Upload Engine

on:
  push:
    branches:
      - main
    paths:
      - 'functions/excel_upload_engine/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Supabase Function Deploy
        run: |
          npm install -g supabase
          supabase functions deploy excel_upload_engine --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
