name: Run Cleanup Script

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: 🧼 Run Cleanup Script
        run: bash cleanup_unused_files.sh
